server {
    listen       80;
    server_name  localhost;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static assets caching
    location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|ico|woff2?)$ {
        expires 1M;
        add_header Cache-Control "public";
    }

    client_max_body_size 10M;
}
